spring.application.name=travelmanager

# ===============================
# JPA & Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Database
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/travelmanager}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JWT
# ===============================
jwt.secret.key=${JWT_SECRET}

# ===============================
# Server
# ===============================
server.port=8081
server.servlet.context-path=/api/v1
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# Mail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# ===============================
# VNPay
# ===============================
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:5173/payment/result}
app.admin.email=${ADMIN_EMAIL:admin@travelmanager.com}
